"""empty message

Revision ID: 808fe0be7170
Revises: f9c822ff47d4
Create Date: 2018-04-05 16:41:43.023402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808fe0be7170'
down_revision = 'f9c822ff47d4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('rsaEncryptedKey', sa.String(length=5000), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'rsaEncryptedKey')
    # ### end Alembic commands ###
