"""empty message

Revision ID: e8b28f8eff96
Revises: 60eaa85d1255
Create Date: 2018-02-24 12:55:36.960189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e8b28f8eff96'
down_revision = '60eaa85d1255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('phoneNumber', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'phoneNumber')
    # ### end Alembic commands ###
