"""empty message

Revision ID: f9c822ff47d4
Revises: 203e3bb15df9
Create Date: 2018-04-05 15:55:42.366906

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f9c822ff47d4'
down_revision = '203e3bb15df9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('signingKey', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'signingKey')
    # ### end Alembic commands ###
